# Generated by Django 5.0.6 on 2024-05-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='snippet',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='code',
        ),
        migrations.AddField(
            model_name='comment',
            name='language',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='linenos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='style',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
